# Generated by Django 5.0.4 on 2024-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Code', models.IntegerField()),
                ('Item_name', models.CharField(max_length=60)),
                ('width', models.CharField(max_length=60)),
                ('GSM_Size', models.CharField(max_length=60)),
                ('Weight_KGS', models.CharField(max_length=60)),
                ('Qty', models.CharField(max_length=60)),
                ('Material_Content', models.CharField(max_length=60)),
                ('Category_End_use', models.CharField(max_length=60)),
                ('OLD_Code', models.CharField(max_length=60)),
                ('Source_vendor_detail', models.CharField(max_length=60)),
                ('Date', models.CharField(max_length=60)),
                ('PRICE', models.CharField(max_length=60)),
                ('GST', models.CharField(max_length=60)),
                ('Thickness', models.CharField(max_length=60)),
                ('Received_Date', models.CharField(max_length=60)),
                ('Received_BY', models.CharField(max_length=60)),
                ('Vendor_Code', models.CharField(max_length=60)),
                ('Remarks', models.CharField(max_length=60)),
                ('Design_Print_GG', models.CharField(max_length=60)),
                ('Qty_in_MTR', models.CharField(max_length=60)),
                ('Micron', models.CharField(max_length=60)),
                ('Count', models.CharField(max_length=60)),
                ('Fiber_Length', models.CharField(max_length=60)),
                ('Mtr', models.CharField(max_length=60)),
                ('Color', models.CharField(max_length=60)),
                ('Shade_No', models.CharField(max_length=60)),
                ('Style_name', models.CharField(max_length=60)),
            ],
        ),
    ]
