# Generated by Django 5.0.4 on 2024-04-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Code', models.IntegerField()),
                ('Item_name', models.CharField(default=' ', max_length=60, null=True)),
                ('Raw_Material', models.CharField(default=' ', max_length=60, null=True)),
                ('Category', models.CharField(default=' ', max_length=60, null=True)),
                ('Material_Content', models.CharField(default=' ', max_length=60, null=True)),
                ('Color', models.CharField(default=' ', max_length=60, null=True)),
                ('Design_Print_GG', models.CharField(default=' ', max_length=60, null=True)),
                ('Width', models.CharField(default=' ', max_length=60, null=True)),
                ('Count', models.CharField(default=' ', max_length=60, null=True)),
                ('Thickness', models.CharField(default=' ', max_length=60, null=True)),
                ('GSM', models.CharField(default=' ', max_length=60, null=True)),
                ('Micron', models.CharField(default=' ', max_length=60, null=True)),
                ('Size', models.CharField(default=' ', max_length=60, null=True)),
                ('Weight_Kgs', models.CharField(default=' ', max_length=60, null=True)),
                ('QTY', models.CharField(default=' ', max_length=60, null=True)),
                ('QTY_MTR', models.CharField(default=' ', max_length=60, null=True)),
                ('Category_End_use', models.CharField(default=' ', max_length=60, null=True)),
                ('OLD_Code', models.CharField(default=' ', max_length=60, null=True)),
                ('Source_vendor_detail', models.CharField(default=' ', max_length=60, null=True)),
                ('date', models.CharField(default=' ', max_length=60, null=True)),
                ('Price', models.CharField(default=' ', max_length=60, null=True)),
                ('Qty_G', models.CharField(default=' ', max_length=60, null=True)),
                ('GST', models.CharField(default=' ', max_length=60, null=True)),
                ('Received_Date', models.CharField(default=' ', max_length=60, null=True)),
                ('Recived_by', models.CharField(default=' ', max_length=60, null=True)),
                ('Vendor_Code', models.CharField(default=' ', max_length=60, null=True)),
                ('Remark', models.CharField(default=' ', max_length=60, null=True)),
            ],
        ),
    ]
