# Generated by Django 5.0.4 on 2024-04-20 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mojo',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='mojoimages'),
            preserve_default=False,
        ),
    ]
