# Generated by Django 5.0.4 on 2024-04-13 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_alter_mojo_category_end_use_alter_mojo_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mojo',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='mojoimages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Category_End_use',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Color',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Count',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Date',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Design_Print_GG',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Fiber_Length',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='GSM_Size',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='GST',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Item_name',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Material_Content',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Micron',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Mtr',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='OLD_Code',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='PRICE',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Qty',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Qty_in_MTR',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Received_BY',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Received_Date',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Remarks',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Shade_No',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Source_vendor_detail',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Style_name',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Thickness',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Vendor_Code',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='Weight_KGS',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='mojo',
            name='width',
            field=models.CharField(default=' ', max_length=60),
        ),
    ]
