# Generated by Django 5.0.4 on 2024-04-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_mojo_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mojo',
            name='images',
        ),
    ]
