# Generated by Django 5.0.4 on 2024-04-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_remove_mojo_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='mojo',
            name='images',
            field=models.ImageField(null=True, upload_to='mojoimages'),
        ),
    ]
