# Generated by Django 5.0.4 on 2024-05-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0004_mojo_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='mojo',
            name='images2',
            field=models.ImageField(null=True, upload_to='mojoimages'),
        ),
        migrations.AddField(
            model_name='mojo',
            name='images3',
            field=models.ImageField(null=True, upload_to='mojoimages'),
        ),
    ]
